-- ============================================================
-- B002 INSERT (2테이블)
-- 실행 전: b002_auth_ddl.sql
-- ============================================================

DELETE FROM TB_B002_AUTH_EXCEL;
DELETE FROM TB_B002_AUTH_EXCEL_DETAIL;

INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D001', '수요예측', '수요예측', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D002', '수요평가', '수요평가', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D003', '수요통계', '수요통계', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D004', '수요수행', '수요수행', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D005', '수요이력', '수요이력', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D006', '생산예측', '생산예측', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D007', '생산평가', '생산평가', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D008', '생산통계', '생산통계', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D009', '공급통계', '공급통계', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D010', '공급수행', '공급수행', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D011', '공급이력', '공급이력', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D012', '예측실행', '예측실행', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D013', '예측평가', '예측평가', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D014', '예측통계', '예측통계', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D015', '기획통계', '기획통계', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D016', '기획수행', '기획수행', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D017', '기획이력', '기획이력', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D018', '실행통계', '실행통계', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D019', '실행수행', '실행수행', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D020', '실행이력', '실행이력', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D021', '배송통계', '배송통계', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D022', '배송수행', '배송수행', 'Y');
INSERT INTO TB_B002_AUTH_EXCEL_DETAIL (DETAIL_ID, DETAIL_NM, DETAIL_AUTH, DETAIL_USE_YN) VALUES ('D023', '배송이력', '배송이력', 'Y');

INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (1,  '박희용', 'X0001', '개발', '수요', 'Y', 'Y', 'D001');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (2,  '박희용', 'X0001', '개발', '수요', 'Y', 'Y', 'D002');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (3,  '박희용', 'X0001', '개발', '수요', 'Y', 'Y', 'D003');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (4,  '박희용', 'X0001', '개발', '수요', 'Y', 'Y', 'D004');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (5,  '박희용', 'X0001', '개발', '수요', 'Y', 'Y', 'D005');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (6,  '박희용', 'X0001', '개발', '생산', 'Y', 'Y', 'D006');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (7,  '박희용', 'X0001', '개발', '생산', 'Y', 'Y', 'D007');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (8,  '박희용', 'X0001', '개발', '생산', 'Y', 'Y', 'D008');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (9,  '김기준', 'X0002', '개발', '공급', 'Y', 'Y', 'D009');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (10, '김기준', 'X0002', '개발', '공급', 'Y', 'Y', 'D010');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (11, '김기준', 'X0002', '개발', '공급', 'Y', 'Y', 'D011');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (12, '김기준', 'X0002', '개발', '예측', 'Y', 'Y', 'D012');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (13, '김기준', 'X0002', '개발', '예측', 'Y', 'Y', 'D013');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (14, '김기준', 'X0002', '개발', '예측', 'Y', 'Y', 'D014');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (15, '구본기', 'X0003', '계획', '기획', 'Y', 'Y', 'D015');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (16, '구본기', 'X0003', '계획', '기획', 'Y', 'Y', 'D016');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (17, '구본기', 'X0003', '계획', '기획', 'Y', 'Y', 'D017');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (18, '김재남', 'X0004', '생산', '실행', 'Y', 'Y', 'D018');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (19, '김재남', 'X0004', '생산', '실행', 'Y', 'Y', 'D019');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (20, '김재남', 'X0004', '생산', '실행', 'Y', 'Y', 'D020');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (21, '정덕희', 'X0005', '조달', '배송', 'Y', 'Y', 'D021');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (22, '정덕희', 'X0005', '조달', '배송', 'Y', 'Y', 'D022');
INSERT INTO TB_B002_AUTH_EXCEL (AUTH_SEQ, EMP_NAME, EMP_NO, DEPT_NAME, AUTH_NAME, AUTH_GRANT, USE_YN, DETAIL_ID) VALUES (23, '정덕희', 'X0005', '조달', '배송', 'Y', 'Y', 'D023');

COMMIT;
