-- ============================================================
-- B002 권한 테이블 (2테이블, 스키마 변경 없음)
-- t1.DETAIL_ID = 부모키
-- t2.DETAIL_ID = t1.DETAIL_ID 와 같은 값으로 여러 행 저장
-- 예: t1.DETAIL_ID = '01', t2.DETAIL_ID = '01' 여러 건
-- ============================================================

CREATE TABLE TB_B002_AUTH_EXCEL (
    AUTH_SEQ      NUMBER(10)      NOT NULL,
    EMP_NAME      VARCHAR2(50)    NOT NULL,
    EMP_NO        VARCHAR2(20)    NOT NULL,
    DEPT_NAME     VARCHAR2(50)    NOT NULL,
    AUTH_NAME     VARCHAR2(50)    NOT NULL,
    AUTH_GRANT    CHAR(1)         DEFAULT 'Y' NOT NULL,
    USE_YN        CHAR(1)         DEFAULT 'Y' NOT NULL,
    DETAIL_ID     VARCHAR2(100)   NOT NULL,
    REG_DT        DATE            DEFAULT SYSDATE,
    UPD_DT        DATE,
    CONSTRAINT PK_TB_B002_AUTH_EXCEL PRIMARY KEY (AUTH_SEQ)
);

CREATE TABLE TB_B002_AUTH_EXCEL_DETAIL (
    DETAIL_ID     VARCHAR2(100)   NOT NULL,
    DETAIL_NM     VARCHAR2(100)   NOT NULL,
    DETAIL_AUTH   VARCHAR2(100)   NOT NULL,
    DETAIL_USE_YN CHAR(1)         DEFAULT 'Y' NOT NULL
);

CREATE INDEX IDX_B002_AUTH_EMP ON TB_B002_AUTH_EXCEL (EMP_NO, AUTH_NAME);
CREATE INDEX IDX_B002_AUTH_DEPT ON TB_B002_AUTH_EXCEL (DEPT_NAME);
CREATE INDEX IDX_B002_AUTH_DETAIL ON TB_B002_AUTH_EXCEL (DETAIL_ID);

CREATE SEQUENCE SEQ_B002_AUTH_EXCEL
    START WITH 100
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;
