-- ============================================================
-- DETAIL_LIST INSERT
-- 실행 전: detail_list_ddl.sql
-- ============================================================

DELETE FROM DETAIL_LIST;

INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('수요예측', '수요예측');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('수요평가', '수요평가');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('수요통계', '수요통계');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('수요수행', '수요수행');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('수요이력', '수요이력');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('생산예측', '생산예측');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('생산평가', '생산평가');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('생산통계', '생산통계');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('공급통계', '공급통계');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('공급수행', '공급수행');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('공급이력', '공급이력');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('예측실행', '예측실행');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('예측평가', '예측평가');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('예측통계', '예측통계');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('기획통계', '기획통계');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('기획수행', '기획수행');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('기획이력', '기획이력');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('실행통계', '실행통계');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('실행수행', '실행수행');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('실행이력', '실행이력');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('배송통계', '배송통계');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('배송수행', '배송수행');
INSERT INTO DETAIL_LIST (DETAIL_AUTH, DETAIL_NM) VALUES ('배송이력', '배송이력');

COMMIT;
